<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>5e6b10cf-dc59-47b2-b297-cd745cdad270</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Marten" Version="9.37.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\BuldingBlocks\BuldingBlocks.csproj" />
  </ItemGroup>

</Project>
