<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\BuldingBlocks\BuldingBlocks.csproj" />
    <ProjectReference Include="..\Ordering.domain\Ordering.domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Data\" />
    <Folder Include="Orders\Commands\" />
    <Folder Include="Orders\EventHandlers\" />
    <Folder Include="Orders\Queries\" />
  </ItemGroup>

</Project>
